export const pseudos = {
  _active: '&:active, &[data-active]',
  _activeLink: '&[aria-current=page]',
  _after: '&::after',
  _autofill: '&:-webkit-autofill',
  _before: '&::before',
  _checked: '&[aria-checked=true], &[data-checked]',
  _disabled: '&[disabled], &[aria-disabled=true], &[data-disabled]',
  _empty: '&::empty',
  _even: '&:nth-of-type(even)',
  _expanded: '&[aria-expanded=true], &[data-expanded]',
  _first: '&:first-of-type',
  _focus: '&:focus, &[data-focus]',
  _focusVisible: '&:focus-visible, [data-focus-visible]',
  _focusWithin: '&:focus-within',
  _fullScreen: '&:fullscreen',
  _grabbed: '&[aria-grabbed=true], &[data-grabbed]',
  _groupActive: '&[role=group]:active &, &[role=group][data-active] &',
  _groupChecked: '&[role=group][data-checked] &',
  _groupDisabled: '&[role=group]:disabled &, [role=group][data-disabled] &',
  _groupFocus: '&[role=group]:focus &, &[role=group][data-focus] &',
  _groupHover: '&[role=group]:hover &, &[role=group][data-hover] &',
  _groupInvalid: '&[role=group][data-invalid] &',
  _hidden: '&[hidden], &[data-hidden]',
  _highlighted: '&[data-highlighted]',
  _hover: '&:hover, &[data-hover]',
  _indeterminate: '&:indeterminate, &[aria-checked=mixed], &[data-indeterminate]',
  _invalid: '&[aria-invalid=true], &[data-invalid]',
  _last: '&:last-of-type',
  _loading: '&[data-loading], &[aria-busy=true]',
  _notFirst: '&:not(:first-of-type)',
  _notLast: '&:not(:last-of-type)',
  _odd: '&:nth-of-type(odd)',
  _placeholder: '&::placeholder',
  _pressed: '&[aria-pressed=true], &[data-pressed]',
  _readOnly: '&[aria-readonly=true], &[readonly], &[data-readonly]',
  _selected: '&[aria-selected=true], &[data-selected]',
  _selection: '&::selection',
  _valid: '&[data-valid], &[data-state=valid]',
  _visited: '&:visited',
};

export type Pseudos = typeof pseudos;
