name: Prerelease

on:
  push:
    branches:
      - changeset-release/main

jobs:
  test:
    name: Build & deploy to Percy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Install Dependencies
        run: yarn --immutable

      - name: Build
        run: yarn build

      - name: Storybook
        run: yarn storybook:build

      - name: Percy
        run: yarn percy storybook ./dist
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
