name: Validate

on: push

jobs:
  test:
    name: Lint & Test
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - name: Checkout Repo
        uses: actions/checkout@main

      - name: Setup Node.js 14.x
        uses: actions/setup-node@main
        with:
          node-version: 14.x

      - name: Install Dependencies
        run: yarn --immutable

      - name: Build
        run: yarn build

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test:jest

      - name: Chromatic
        run: |
          yarn build-storybook
          yarn chromatic --storybook-build-dir dist-storybook --exit-zero-on-changes --auto-accept-changes main
        env:
          CHROMATIC_PROJECT_TOKEN: ${{ secrets.MANIFEST_UI_CHROMATIC_PROJECT_TOKEN }}
