name: yarn-deduplicate

on:
  pull_request:
    paths:
      - "yarn.lock"

jobs:
  dedupe:
    runs-on: ubuntu-latest
    name: Deduplicate
    environment: pull_request_unsafe

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: yarn-deduplicate
        id: deduplicate
        run: |
          yarn
          yarn yarn-deduplicate
          echo "::set-output name=diff::$(git status --short yarn.lock)"

      - name: Commit dedupe
        if: steps.deduplicate.outputs.diff
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: "chore: yarn-deduplicate"
          branch: ${{ github.head_ref }}
